name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          username: itsgreylolol
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: itsgreylolol/publish-packages/chatbot
          tag_with_sha: true
